apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: websites.extensions.example.com
  namespace: default
spec:
  scope: Namespaced
  group: extensions.example.com
  version: v1
  names:
    kind: Website
    listKind: WebsiteList
    shortNames: 
      - wb
      - web
    singular: website
    plural: websites