apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: iris-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iris-deploy-v1
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30
